version: "2.4"

services:
  mysql:
    image: mysql:5.7.21
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=herz_select
#    - MYSQL_USER=root
    - MYSQL_PASSWORD=root
    ports:
    - 3306:3306
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-uroot", "-proot", "-e", "select 1;"]
      interval: 5s
      timeout: 5s
      retries: 5